In [11]:
import numpy as np

# 1D array
arr1d = np.array([10, 20, 30])
print("1D Array:\n", arr1d)

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2d)

# 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", arr3d)

print("Shape of arr2d:", arr2d.shape)    # (2 rows, 3 columns)
print("Data type of arr2d:", arr2d.dtype)

arr_float = np.array([1, 2, 3], dtype=float)
print("Float array:", arr_float)
print("Element at [1,2]:", arr2d[1, 2])  # 6

# Slice rows and columns
print("First row:", arr2d[0])
print("First column:", arr2d[:, 0])

1D Array:
 [10 20 30]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of arr2d: (2, 3)
Data type of arr2d: int32
Float array: [1. 2. 3.]
Element at [1,2]: 6
First row: [1 2 3]
First column: [1 4]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr.reshape(3, 2)  # 3 rows, 2 columns
print("Reshaped array:\n", reshaped)

flat = arr.flatten()
print("Flattened array:", flat)

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
Flattened array: [1 2 3 4 5 6]


In [15]:
original = np.array([1, 2, 3])

copy_arr = original.copy()
view_arr = original.view()

original[0] = 99

print("Original:", original)     # [99  2  3]
print("Copy:", copy_arr)         # [ 1  2  3] → not affected
print("View:", view_arr)

Original: [99  2  3]
Copy: [1 2 3]
View: [99  2  3]


In [19]:
import numpy as np

# Creating two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
sum_arr = arr1 + arr2
print("Sum of arr1 and arr2:", sum_arr)

# Subtraction
diff_arr = arr1 - arr2
print("Difference between arr1 and arr2:", diff_arr)

# Multiplication
prod_arr = arr1 * arr2
print("Product of arr1 and arr2:", prod_arr)

# Division
quot_arr = arr1 / arr2
print("Division of arr1 by arr2:", quot_arr)

Sum of arr1 and arr2: [5 7 9]
Difference between arr1 and arr2: [-3 -3 -3]
Product of arr1 and arr2: [ 4 10 18]
Division of arr1 by arr2: [0.25 0.4  0.5 ]


In [27]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
elementwise_add = arr1 + arr2
print("Element-wise Addition:\n", elementwise_add)

# Matrix multiplication
print("Matrix Multiplication:\n", matrix_mult)

Element-wise Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Sum of all elements
total_sum = arr.sum()
print("Total Sum:", total_sum)

# Mean of all elements
mean_val = arr.mean()
print("Mean Value:", mean_val)

# Standard deviation
std_dev = arr.std()
print("Standard Deviation:", std_dev)

# Min and Max values
min_val = arr.min()
max_val = arr.max()
print("\nMin Value:", min_val)
print("Max Value:", max_val)

# Sum along columns (axis=0) and rows (axis=1)
sum_cols = arr.sum(axis=0)
sum_rows =arr.sum(axis=1)
print("\nSum along columns:", sum_cols)
print("Sum along rows:", sum_rows)

Total Sum: 45
Mean Value: 5.0
Standard Deviation: 2.581988897471611

Min Value: 1
Max Value: 9

Sum along columns: [12 15 18]
Sum along rows: [ 6 15 24]
