In [9]:
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print(arr)
 
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print('\nRank Two Array\n', arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print('\nRank One Array with tuple\n',arr)

[1 2 3]

Rank Two Array
 [[1 2 3]
 [4 5 6]]

Rank One Array with tuple
 [1 3 2]


In [13]:
import numpy as np
 
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)
 
# Printing elements at
# specific Indices
arr3 = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [ ]:
import numpy as np
 
# Defining Array 1
a = np.array([[1, 5],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a. sum ())
 
# Adding two arrays
# Performing Binary Operations
print ("\nArray sum:\n", a + b)


Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [17]:
import numpy as np
 
# Integer datatype
x = np.array([1, 2])  
print(x.dtype)         
 
# Float datatype
x = np.array([1.0, 2.0]) 
print(x.dtype)  
 
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print(x.dtype)

int32
float64
int64


In [19]:
import numpy as np

# Create arrays of int32 and int64
arr32 = np.array([1, 2, 3], dtype=np.int32)
arr64 = np.array([1, 2, 3], dtype=np.int64)

# Print their data types
print("Data Type of arr32:", arr32.dtype)
print("Data Type of arr64:", arr64.dtype)

# Print the size of each element in bytes
print("Size of each element in arr32 (bytes):", arr32.itemsize)
print("Size of each element in arr64 (bytes):", arr64.itemsize)

# Value ranges
print("int32 range: ", np.iinfo(np.int32).min, "to", np.iinfo(np.int32).max)
print("int64 range: ", np.iinfo(np.int64).min, "to", np.iinfo(np.int64).max)


Data Type of arr32: int32
Data Type of arr64: int64
Size of each element in arr32 (bytes): 4
Size of each element in arr64 (bytes): 8
int32 range:  -2147483648 to 2147483647
int64 range:  -9223372036854775808 to 9223372036854775807


In [55]:
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print('Addition of two Arrays\n',Sum)
 
# Addition of all Array elements
Sum1 = np.sum(arr1)
print('\nAddition of all Array elements\n',Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print('\nSquare root of Array\n',Sqrt)
 
# Transpose of Array
Trans_arr = arr1.T
print('\nTranspose of Array\n',Trans_arr)


Addition of two Arrays
 [[ 7. 13.]
 [ 4. 14.]]

Addition of all Array elements
 19.0

Square root of Array
 [[2.         2.64575131]
 [1.41421356 2.44948974]]

Transpose of Array
 [[4. 2.]
 [7. 6.]]


In [64]:
import numpy as np 

# creating array 
arr = np.array([2, 4, 6, 8, 10]) 

# creating copy of array 
c = arr.copy() 

# both arr and c have different id 
print("id of arr", id(arr)) 
print("id of c", id(c)) 

# changing original array 
# this will not effect copy 
arr[0] = 12

# printing array and copy 
print("original array- ", arr) 
print("copy- ", c) 


id of arr 2577491684560
id of c 2577473186256
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [66]:
import numpy as np 

# creating array 
arr = np.array([2, 4, 6, 8, 10]) 

# assigning arr to nc 
nc = arr 

# both arr and nc have same id 
print("id of arr", id(arr)) 
print("id of nc", id(nc)) 

# updating nc 
nc[0]= 12

# printing the values 
print("original array- ", arr) 
print("assigned array- ", nc) 


id of arr 2577491683312
id of nc 2577491683312
original array-  [12  4  6  8 10]
assigned array-  [12  4  6  8 10]


In [68]:
# importing the module
import numpy as np

# creating an array
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)

# appending to the array
arr = np.append(arr, [7])
print('Array after appending : ', arr)


Original Array :  [1 8 3 3 5]
Array after appending :  [1 8 3 3 5 7]


In [70]:
# importing the module
import numpy as np

# creating an array
arr1 = np.array([1, 2, 3])
print('First array is : ', arr1)

# creating another array
arr2 = np.array([4, 5, 6])
print('Second array is : ', arr2)

# appending arr2 to arr1
arr = np.append(arr1, arr2)
print('Array after appending : ', arr)


First array is :  [1 2 3]
Second array is :  [4 5 6]
Array after appending :  [1 2 3 4 5 6]


In [72]:
# importing the module
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

combined = np.concatenate((arr1, arr2), axis=0)
print(combined)


[[1 2]
 [3 4]
 [5 6]]


In [74]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

combined = np.concatenate((arr1, arr2), axis=1)
print("Column-wise Concatenation:\n", combined)


Column-wise Concatenation:
 [[1 2 5 6]
 [3 4 7 8]]


In [76]:

vstacked = np.vstack((arr1, arr2))
print("Using vstack:\n", vstacked)


Using vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [78]:
hstacked = np.hstack((arr1, arr2))
print("Using hstack:\n", hstacked)


Using hstack:
 [[1 2 5 6]
 [3 4 7 8]]


In [80]:
# importing the module
import numpy as np

arr = np.array([1, 2, 3])
arr_float = np.array([4.0, 5.0])

combined = np.append(arr, arr_float)
print(combined) # Output: [1. 2. 3. 4. 5.]


[1. 2. 3. 4. 5.]


In [82]:
# importing the module
import numpy as np

# create an array
arr = np.arange(1, 13).reshape(2, 6)
print('Original Array')
print(arr, '\n')

# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
print('Array to be appended column wise')
print(col)
arr_col = np.append(arr, col, axis=0)
print('Array after appending the values column wise')
print(arr_col, '\n')

# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
print('Array to be appended row wise')
print(row)
arr_row = np.append(arr, row, axis=1)
print('Array after appending the values row wise')
print(arr_row)


Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

Array to be appended column wise
[[ 5  6  7  8  9 10]]
Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

Array to be appended row wise
[[1]
 [2]]
Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


In [88]:
import numpy as np

an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

comparison = an_array == another_array
equal_arrays = comparison.all()

print(equal_arrays)


True


In [90]:
import numpy as np


a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

print("Array a: ", a)
print("Array b: ", b)

print("a > b")
print(np.greater(a, b))

print("a >= b")
print(np.greater_equal(a, b))

print("a < b")
print(np.less(a, b))

print("a <= b")
print(np.less_equal(a, b))


Array a:  [101  99  87]
Array b:  [897  97 111]
a > b
[False  True False]
a >= b
[False  True False]
a < b
[ True False  True]
a <= b
[ True False  True]


In [92]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


# Comparing the arrays
if np.array_equal(arr1, arr2):
	print("Equal")
else:
	print("Not Equal")


Equal
